import { createContext, useContext, useState } from 'react';

const LangContext = createContext();

export const translations = {
  en: {
    nav: {
      home:     'Home',
      about:    'About',
      projects: 'Projects',
      learning: 'Learning',
      contact:  'Contact',
    },
    home: {
      statusOnline:    'Available for work',
      statusLocation:  'DOUALA, CAMEROON',
      headline1:       'AI AGENT',
      headline2:       'DEVELOPER',
      sub:             '& Software Engineer',
      intro:           "I create intelligent software that learns and improves over time. Currently completing my Master's degree in Artificial Intelligence at IUT de Douala, my goal is to become one of Africa's leading experts in AI and machine learning.",
      cta1:            'See My Work',
      cta2:            'Get In Touch',
      stackLabel:      'Tools & Technologies I Use',
      dataLabel:       'AI & Data Science',
      statsLabel:      'At a Glance',
      stat1Label:      'Days of Daily Coding',
      stat2Label:      'Active Projects',
      stat3Label:      'Technologies Mastered',
    },
    about: {
      sectionLabel:    'About Me',
      headline:        'WHO I AM',
      intro:           "I am a software engineer who specializes in artificial intelligence, the technology reshaping every industry today. I don't just write code; I build systems that help people make better decisions, faster.",
      timelineLabel:   'My Journey',
      traitsLabel:     'My Strengths',
      quoteLabel:      'A Personal Note',
      quote:           "My grandmother never touched a computer. But the 4 years I spent with her taught me something no university can: that anything worth building requires showing up every single day, without fail. That lesson runs through everything I do.",
      quoteAuthor:     'Merveille Nzoyem',
      t1year:          'The Beginning',
      t1title:         'Growing Up Learning Discipline',
      t1desc:          '4 years living with my grandmother shaped who I am. She taught me patience, consistency, and the value of hard work. These are the same qualities that make a great engineer and I carry them into every project.',
      t2year:          'University',
      t2title:         'Bachelor\'s Degree in Software Engineering',
      t2desc:          'I studied how to design, build, and maintain software systems. I learned how computers think, how to write clean and efficient code, and how to solve complex problems in a structured way.',
      t3year:          'Today',
      t3title:         "Master's Degree in AI IUT de Douala",
      t3desc:          'I am now specializing in artificial intelligence  teaching machines to recognize patterns, make predictions, and automate decisions. My main project, SkillGap AI, applies these skills to the job market.',
      t4year:          'Where I\'m Headed',
      t4title:         'Senior AI Engineer',
      t4desc:          'My goal is to become a recognized expert in AI at the international level  building systems that work at large scale and have real impact on people\'s lives, starting from Douala.',
    },
    projects: {
      sectionLabel:    'My Projects',
      headline:        'WHAT I BUILD',
      subheadline:     'Real problems. Real solutions. Real impact.',
      project1name:    'SkillGap AI',
      project1tag:     'Main Project · AI Tool',
      project1status:  'In Progress',
      project1desc:    'SkillGap AI is a smart platform that scans thousands of job offers, identifies the skills employers actually want, and tells you exactly what to learn to land the job you want tailored to your profile and your city.',
      project1f1:      'Reads and understands job listings automatically',
      project1f2:      'Shows which skills are most in demand by sector',
      project1f3:      'Creates a personalized learning plan for each user',
      project1f4:      'Live dashboard showing market trends',
      project2name:    '100 Days of Coding',
      project2tag:     'Ongoing Challenge',
      project2status:  '41+ Days Completed',
      project2desc:    'Every single day for 100 days, I write code and study AI. No skipping. No excuses. Each day builds on the last. I share my progress publicly so others can follow along and learn too.',
      project2f1:      'Covers prediction, classification, and data grouping',
      project2f2:      'Builds algorithms from the ground up to truly understand them',
      project2f3:      'Applies each concept to a real mini-project',
      project2f4:      'Everything documented and shared publicly',
      project3name:    'AI Automation Systems',
      project3tag:     'Technical Expertise',
      project3status:  'Fully Operational',
      project3desc:    'I design and build systems that automate repetitive tasks using AI. Think of it as creating a smart assistant that can handle workflows, connect different software tools together, and run without constant human supervision.',
      project3f1:      'Automates multi-step workflows without manual effort',
      project3f2:      'Connects AI assistants to real data and tools',
      project3f3:      'Packaged for easy and reliable deployment anywhere',
      project3f4:      'Integrates with third-party apps and services',
    },
    learning: {
      sectionLabel:    'Learning & Growth',
      headline:        'GROWING IN THE OPEN',
      intro:           "I share my learning journey publicly  the wins, the struggles, and everything in between. I believe that knowledge only multiplies when it's shared. If my path can help even one person, it's worth documenting.",
      readingLabel:    'Books That Shaped Me',
      roadmapLabel:    'What\'s Next For Me',
      youtubeLabel:    'Launching 2027',
      youtubeTitle:    'YouTube Channel',
      youtubeDesc:     "I'm building a YouTube channel where I'll share everything I learn about AI in plain language no unnecessary complexity. I want to show that world-class AI expertise can come from anywhere, including Douala.",
      book1title:      'Think and Grow Rich',
      book1author:     'Napoleon Hill',
      book1take:       'Success starts with a clear goal and the stubbornness to pursue it daily. I apply this to my AI learning: clear target, consistent action, no shortcuts.',
      book2title:      'The One Thing',
      book2author:     'Gary Keller',
      book2take:       "Stop doing everything. Pick one priority and go deep on it. My one thing right now: becoming a world-class AI engineer. I say no to distractions so I can say yes to mastery.",
      book3title:      'Deep Work',
      book3author:     'Cal Newport',
      book3take:       "The ability to focus without distraction is a superpower. I protect my focused work hours like they're sacred because that's when the real progress happens.",
      r1year:          '2024–2025',
      r1item:          "Master's in AI + 100 Days of Coding + Launching SkillGap AI",
      r2year:          '2025–2026',
      r2item:          'Going deeper into AI: image recognition, language models, and advanced machine learning',
      r3year:          '2026–2027',
      r3item:          'Contributing to open-source AI projects and publishing research',
      r4year:          '2027',
      r4item:          'Launching YouTube channel sharing the African AI journey with the world',
      r5year:          '2028+',
      r5item:          'Senior AI Engineer building systems that impact millions of people',
    },
    contact: {
      sectionLabel:    'Contact',
      headline:        "LET'S WORK TOGETHER",
      intro:           "Have a project in mind, a job opportunity, or just want to say hello? I read every message and reply within 24 hours.",
      namePH:          'Your full name',
      emailPH:         'your@email.com',
      subjectPH:       'What is this about?',
      messagePH:       'Tell me about your project, idea, or question...',
      submit:          'Send My Message →',
      successTitle:    'Message Sent!',
      successMsg:      'Thank you for reaching out. I will get back to you within 24 hours.',
      openTo:          "I'm available for",
      c1:              'Freelance AI & software projects',
      c2:              'Research and academic collaborations',
      c3:              'Full-time or remote job opportunities',
      c4:              'Mentoring and knowledge sharing',
      location:        'Douala, Cameroon 🇨🇲',
      availability:    'Freelance · Open to opportunities',
      response:        'Within 24 hours',
    },
  },

  fr: {
    nav: {
      home:     'Accueil',
      about:    'À propos',
      projects: 'Projets',
      learning: 'Formation',
      contact:  'Contact',
    },
    home: {
      statusOnline:    'Disponible',
      statusLocation:  'DOUALA, CAMEROUN',
      headline1:       'AI AGENT',
      headline2:       'DEVELOPER',
      sub:             '& Ingénieur Logiciel',
      intro:           "Je crée des logiciels intelligents qui apprennent et s'améliorent avec le temps. En Master Intelligence Artificielle à l'IUT de Douala mon objectif est de devenir l'un des experts IA de référence sur le continent africain.",
      cta1:            'Voir mes projets',
      cta2:            'Me contacter',
      stackLabel:      'Outils & technologies que j\'utilise',
      dataLabel:       'IA & Science des données',
      statsLabel:      'En bref',
      stat1Label:      'Jours de code quotidien',
      stat2Label:      'Projets actifs',
      stat3Label:      'Technologies maîtrisées',
    },
    about: {
      sectionLabel:    'À propos de moi',
      headline:        'QUI JE SUIS',
      intro:           "Je suis un ingénieur logiciel spécialisé en intelligence artificielle , la technologie qui redéfinit tous les secteurs d'activité aujourd'hui. Je ne me contente pas d'écrire du code , je construis des systèmes qui aident les gens à prendre de meilleures décisions, plus vite.",
      timelineLabel:   'Mon parcours',
      traitsLabel:     'Mes points forts',
      quoteLabel:      'Une note personnelle',
      quote:           "Ma grand-mère n'a jamais touché un ordinateur. Mais les 4 ans que j'ai passés avec elle m'ont appris quelque chose qu'aucune université ne peut enseigner : que tout ce qui vaut la peine d'être construit demande de se présenter chaque jour, sans faute. Cette leçon guide tout ce que je fais.",
      quoteAuthor:     'Merveille Nzoyem',
      t1year:          'Les débuts',
      t1title:         'L\'enfance Apprendre la discipline',
      t1desc:          '4 ans de vie avec ma grand-mère ont forgé ma personnalité. Elle m\'a appris la patience, la constance et la valeur du travail bien fait. Ce sont exactement les qualités d\'un bon ingénieur  et je les apporte dans chaque projet.',
      t2year:          'Université',
      t2title:         'Licence en Génie Logiciel',
      t2desc:          'J\'ai appris à concevoir, construire et maintenir des systèmes informatiques. Comment les ordinateurs fonctionnent, comment écrire du code propre et efficace, et comment résoudre des problèmes complexes de façon structurée.',
      t3year:          'Aujourd\'hui',
      t3title:         'Master IA IUT de Douala',
      t3desc:          'Je me spécialise maintenant en intelligence artificielle  apprendre aux machines à reconnaître des tendances, faire des prédictions et automatiser des décisions. Mon projet principal, SkillGap AI, applique ces compétences au marché de l\'emploi.',
      t4year:          'La suite',
      t4title:         'Ingénieur IA Senior',
      t4desc:          'Mon objectif est de devenir un expert IA reconnu à l\'international  construire des systèmes qui fonctionnent à grande échelle et ont un impact réel sur la vie des gens, en partant de Douala.',
    },
    projects: {
      sectionLabel:    'Mes projets',
      headline:        'CE QUE JE CONSTRUIS',
      subheadline:     'De vrais problèmes. De vraies solutions. Un vrai impact.',
      project1name:    'SkillGap AI',
      project1tag:     'Projet principal · Outil IA',
      project1status:  'En cours',
      project1desc:    'SkillGap AI est une plateforme intelligente qui analyse des milliers d\'offres d\'emploi, identifie les compétences réellement recherchées par les recruteurs, et vous dit exactement quoi apprendre pour décrocher le poste que vous visez  adapté à votre profil et votre ville.',
      project1f1:      'Lit et comprend automatiquement les offres d\'emploi',
      project1f2:      'Montre quelles compétences sont les plus demandées par secteur',
      project1f3:      'Crée un plan d\'apprentissage personnalisé pour chaque utilisateur',
      project1f4:      'Tableau de bord en direct affichant les tendances du marché',
      project2name:    '100 Jours de Code',
      project2tag:     'Défi en cours',
      project2status:  '41+ jours réalisés',
      project2desc:    'Chaque jour pendant 100 jours, j\'écris du code et j\'étudie l\'IA. Chaque journée s\'appuie sur la précédente. Je partage ma progression publiquement pour que d\'autres puissent suivre et apprendre aussi.',
      project2f1:      'Couvre la prédiction, la classification et le regroupement de données',
      project2f2:      'Reconstruit les algorithmes depuis zéro pour vraiment les comprendre',
      project2f3:      'Applique chaque concept à un mini-projet concret',
      project2f4:      'Tout est documenté et partagé publiquement',
      project3name:    'Systèmes d\'automatisation IA',
      project3tag:     'Expertise technique',
      project3status:  'Opérationnel',
      project3desc:    'Je conçois et construis des systèmes qui automatisent les tâches répétitives grâce à l\'IA. Imaginez un assistant intelligent capable de gérer des processus entiers, de connecter différents outils logiciels entre eux, et de fonctionner sans surveillance humaine constante.',
      project3f1:      'Automatise des processus complexes sans intervention manuelle',
      project3f2:      'Connecte des assistants IA à des données et outils réels',
      project3f3:      'Prêt à être déployé facilement et de façon fiable partout',
      project3f4:      'S\'intègre avec des applications et services tiers',
    },
    learning: {
      sectionLabel:    'Formation & Croissance',
      headline:        'J\'APPRENDS EN TRANSPARENCE',
      intro:           "Je partage mon parcours d'apprentissage ouvertement  les réussites, les difficultés, et tout ce qui se passe entre les deux. Je crois que la connaissance se multiplie quand on la partage. Si mon chemin peut aider une seule personne, ça vaut la peine de le documenter.",
      readingLabel:    'Livres qui m\'ont transformé',
      roadmapLabel:    'Ce qui m\'attend',
      youtubeLabel:    'Lancement en 2027',
      youtubeTitle:    'Chaîne YouTube',
      youtubeDesc:     "Je prépare une chaîne YouTube où je partagerai tout ce que j'apprends sur l'IA dans un langage accessible  sans complexité inutile. Je veux montrer qu'une expertise IA de niveau mondial peut venir de n'importe où, y compris de Douala.",
      book1title:      'Réfléchissez et devenez riche',
      book1author:     'Napoleon Hill',
      book1take:       'Le succès commence par un objectif clair et l\'obstination de le poursuivre chaque jour. J\'applique cela à mon apprentissage : cible précise, action constante, pas de raccourcis.',
      book2title:      'The One Thing',
      book2author:     'Gary Keller',
      book2take:       "Arrêtez de tout faire en même temps. Choisissez une priorité et allez-y à fond. Ma priorité en ce moment : devenir un ingénieur IA de classe mondiale. Je dis non aux distractions pour dire oui à la maîtrise.",
      book3title:      'Deep Work',
      book3author:     'Cal Newport',
      book3take:       "La capacité à se concentrer sans distraction est un superpouvoir. Je protège mes heures de travail intensif comme si elles étaient sacrées parce que c'est là que les vrais progrès se font.",
      r1year:          '2025–2026',
      r1item:          'Master IA + 100 Jours de Code + lancement de SkillGap AI',
      r2year:          '2026–2027',
      r2item:          'Approfondissement en IA : reconnaissance d\'images, modèles de langage, apprentissage avancé',
      r3year:          '2027–2028',
      r3item:          'Contribution à des projets IA open-source et publication de travaux de recherche',
      r4year:          '2029',
      r4item:          'Lancement de la chaîne YouTube partager le parcours IA africain avec le monde',
      r5year:          '2030+',
      r5item:          'Ingénieur IA Senior  construire des systèmes qui touchent des millions de personnes',
    },
    contact: {
      sectionLabel:    'Contact',
      headline:        'TRAVAILLONS ENSEMBLE',
      intro:           "Vous avez un projet, une opportunité à me proposer, ou simplement envie d'échanger ? Je lis tous les messages et réponds sous 24 heures.",
      namePH:          'Votre nom complet',
      emailPH:         'votre@email.com',
      subjectPH:       'De quoi s\'agit-il ?',
      messagePH:       'Parlez-moi de votre projet, votre idée ou votre question...',
      submit:          'Envoyer mon message →',
      successTitle:    'Message envoyé !',
      successMsg:      'Merci de m\'avoir contacté. Je vous répondrai dans les 24 heures.',
      openTo:          'Je suis disponible pour',
      c1:              'Projets freelance en IA et développement logiciel',
      c2:              'Collaborations de recherche et académiques',
      c3:              'Opportunités d\'emploi à temps plein ou à distance',
      c4:              'Mentoring et partage de connaissances',
      location:        'Douala, Cameroun 🇨🇲',
      availability:    'Freelance · Ouvert aux opportunités',
      response:        'Sous 24 heures',
    },
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState('fr');
  const t = translations[lang];
  const toggle = () => setLang(l => (l === 'fr' ? 'en' : 'fr'));

  return (
    <LangContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
